### ISSUE TITLE
Vector Normalization

### ISSUE THREAD

**Issue by borondics** [markotoplak/orange-spectroscopy#130]
Guys,

In the preprocess.py at line 290 (_NormalizeCommon) there seems to be a mistake, but I might be wrong, so I'll not change anything. There are "if"s that check the same condition (then why have two) and I am not sure about the indentation either (data.X...). Not sure if it was @stuart-cls or @markotoplak who did the original version, but could you have a look?

f

**Comment by stuart-cls** [comment]
`git blame` is your friend :) https://github.com/markotoplak/orange-infrared/blame/master/orangecontrib/infrared/preprocess.py

Looks like @markotoplak added it to handle NaNs, since the `sknormalize` function doesn't like them. My reading is that it strips the NaNs, normalizes with `sknormalize` and then puts the NaNs back. The `if` statements are there for datasets that don't have NaNs, in which case only `sknormalize` is called.

Hope that helps!
